import { Anek_Latin, Inria_Sans } from 'next/font/google'
import "./globals.css";
import Topo from "./components/Topo";
import Footer from './components/Footer';

const anek = Anek_Latin({
  subsets: ['latin'],
  display: 'swap',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800'],
})

const inria = Inria_Sans({
  subsets: ['latin'],
  display: 'swap',
  weight: ['300', '400', '700'],
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br" className={anek.className}>
      <body className={inria.className}>
        <Topo />
        {children}
        <Footer />
      </body>
    </html>
  );
}